[package]
name = "regulator-cli"
version = "0.1.0"
edition = "2024"
authors = ["Joss Duff"]

[dependencies]
clap.workspace = true
reqwest.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
